# Prod overwrite values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

init:
  sync:
    enabled: false

resources:
  requests:
    cpu: 1000m
    memory: 4Gi
  limits:
    cpu: 2000m
    memory: 12Gi

persistence:
  enabled: true
  lotus:
    size: "500Gi"
    storageClassName: gp2 # ebs-sc
    accessModes:
      - ReadWriteOnce
