# Minikube overwrite values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

init:
  sync:
    enabled: false

resources:
  requests:
    cpu: 1000m
    memory: 2.5Gi
  limits:
    cpu: 2000m
    memory: 4Gi

persistence:
  enabled: true
  lotus:
    size: "30Gi"
    storageClassName: csi-hostpath-sc
    accessModes:
      - ReadWriteOnce
