kind: Pod
apiVersion: v1
metadata:
  name: chainwatch-api-server
  namespace: chainwatch
  labels:
    app: chainwatch-api-server
spec:
  containers:
    - name: chainwatch-api-server
      image: openworklabs/chainwatch-api-server:0.1.0
      env:
        - name: LOTUS_DB
          valueFrom:
            secretKeyRef:
              name: chainwatch-secret
              key: LOTUS_DB
